### ISSUE TITLE
worst config ever

### ISSUE THREAD

**Issue by OguzhanUmutlu** [XGDavid/XGTAntiXRay#2]
https://poggit.pmmp.io/ci/OguzhanUmutlu/BlockLogger/
my anticheat is best xd dont try to copy to beat me 👍

**Comment by XGDavid** [comment]
wtf

**Comment by XGDavid** [comment]
your plugin has uploaded 42 min ago, wtf

**Comment by OguzhanUmutlu** [comment]
yep 42 min
i made this plugin in 1 hour and better than you :d i am saying that

**Comment by XGDavid** [comment]
omg ruski
